-- LEVEL 2 – QUESTION 1

-- Find the total revenue generated by each customer.
SELECT c.customer_id, c.customer_name, SUM(quantity * price) AS total_revenue
FROM customers c 
INNER JOIN orders o 
	ON c.customer_id = o.customer_id 
INNER JOIN order_items i
    ON i.order_id = o.order_id
INNER JOIN products p 
    ON p.product_id  = i.product_id 
GROUP BY   c.customer_id, c.customer_name;



-- LEVEL 2 – QUESTION 2
-- Find customers who have placed more than 2 orders.
SELECT 
	c.customer_id, 
    c.customer_name, 
    COUNT(o.order_id) AS total_orders
FROM customers c 
INNER JOIN orders o 
    ON c.customer_id = o.customer_id
GROUP BY 
	c.customer_id, 
    c.customer_name
HAVING COUNT(o.order_id) > 2;



-- LEVEL 2 – QUESTION 3
-- Find the most expensive product purchased by each customer.
SELECT 
    c.customer_id, 
    c.customer_name, 
    MAX(p.price) AS most_expensive_product
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
INNER JOIN order_items i
    ON i.order_id = o.order_id
INNER JOIN products p 
    ON p.product_id = i.product_id 
GROUP BY 
    c.customer_id, 
    c.customer_name;



--NOTE : “Because a customer may have purchased multiple products, SQL cannot safely choose one product_name.” That's why we used the subquery 
-- Most expensive product purchased by each customer (using subquery)
SELECT 
    c.customer_id,
    c.customer_name,
    p.product_name,
    p.price
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
INNER JOIN order_items i
    ON i.order_id = o.order_id
INNER JOIN products p
    ON p.product_id = i.product_id
INNER JOIN (
    SELECT 
        c.customer_id,
        MAX(p.price) AS max_price
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_items i
        ON i.order_id = o.order_id
    INNER JOIN products p
        ON p.product_id = i.product_id
    GROUP BY c.customer_id
) mp
    ON mp.customer_id = c.customer_id
   AND mp.max_price = p.price;




